config/routes.rb
Dwollotron::Application.routes.draw do
  resources :accounts do
    member do
      post 'queue'
      post 'cancel_current_payment'
    end
  end
  resources :payments, only: [:show]
  root to: redirect("/accounts")
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  include PaymentStateMachine
  
  belongs_to :account
  has_many :payment_events
  
  validates_presence_of :account_id, :started_at, :effective_at
  
  attr_accessor :raw_response, :remote_transaction_id, :error
  
  def log_payment_event(transition)
    event = payment_events.create!(:created_at => Time.now, 
                           :from_state => transition.from_name, 
                           :to_state => transition.to_name, 
                           :remote_transaction_id => remote_transaction_id, 
                           :raw_response => raw_response,
                           :error => error)
    self.raw_response = nil
    self.remote_transaction_id = nil
    self.error = nil
    event
  end
  
  def has_existing_payments_in_the_same_effective_month?
    account.payments.where("effective_at >= ? and effective_at <= ? and state = ?", effective_at.getgm.beginning_of_month, effective_at.getgm.end_of_month, :completed).count > 0
  end
  
  def call_remote_dwolla_api(args=nil)
    raise InvalidStateError unless self.processing?
    
    return handle_duplicate! if has_existing_payments_in_the_same_effective_month?
    
    begin
      amount = account.scheduled_amount_at(effective_at).amount
      # call the dwolla api
      complete!
    rescue Exception => ex
      self.error = {:exception => ex.inspect, :trace => ex.backtrace}
      handle_error!
    end
  end
  
  def cancel_duplicate(args=nil)
    raise InvalidStateError unless self.duplicate?
    account.cancel_current_payment
  end 
  
  def complete_records(args=nil)
    raise InvalidStateError unless self.completed?
    update_attributes(:completed_at => Time.now)
    account.complete_payment!
  end
  
  def set_account_error(args=nil)
    raise InvalidStateError unless self.error?
    account.handle_error!
  end
  
  class InvalidStateError < StandardError
  end
  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def show
    @payment = Payment.find(params[:id])
    @payment_events = @payment.payment_events.order(:created_at)
  end

end

app/views/payments/show.html.haml
%ul.breadcrumb
  %li
    =link_to "Account", account_path(@payment.account)
    %span.divider
      \/
  %li.active
    %a{:href=>"#"}
      Payment Details
%h1 
  Payment Details
  
  
%form.form-horizontal{:style=>"margin-top: 20px"}
  %fieldset
    .control-group
      %label
        Payment ID
      .controls
        %span{:class=>"uneditable-input"}
          =@payment.id
    .control-group
      %label
        Account ID
      .controls
        %span{:class=>"uneditable-input"}
          =@payment.account.id
    .control-group
      %label
        State
      .controls
        %span{:class=>"uneditable-input"}
          =@payment.state
    .control-group
      %label
        Started at
      .controls
        %span{:class=>"uneditable-input"}
          =@payment.started_at
    .control-group
      %label
        Completed at
      .controls
        %span{:class=>"uneditable-input"}
          =@payment.completed_at
    .control-group
      %label
        Effective at
      .controls
        %span{:class=>"uneditable-input"}
          =@payment.effective_at

%table.table.table-bordered
  %thead
    %tr
      %th ID
      %th Created At
      %th From State
      %th To State
      %th Remote Transaction ID
      %th Raw Response
      %th Error
  %tbody
    -@payment_events.each do |event|
      %tr
        %td
          =event.id
        %td 
          =event.created_at
        %td
          =event.from_state
        %td
          =event.to_state
        %td
          =event.remote_transaction_id
        %td
          =event.raw_response
        %td
          =event.error.inspect